### ISSUE TITLE
Server Crashes When Logging In

### ISSUE THREAD

**Issue by merktassel** [MKS-PostgreSQL/open2#51]
```
Magic happens on 8080
Database is connected
/app/node_modules/mysql/lib/protocol/Parser.js:77
       ^
       throw err; // Rethrow non-MySQL errors
TypeError: Cannot read property 'password' of undefined
   at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
   at Query.EofPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
   at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:280:23)

   at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:73:12)
   at Query._callback (/app/index.js:21:48)
   at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
   at Query._handleFinalResultPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
   at emitOne (events.js:90:13)
   at Socket.emit (events.js:182:7)
```

**Comment by merktassel** [comment]
Somebody must have cleared the database again. The server crashed when trying to sign in with a nonexistent account (#25), but after signing up and trying again it worked fine.
